services:
  citus-coordinator:
    image: citusdata/citus:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/citus-coordinator-data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - citus-net

  citus-worker-1:
    image: citusdata/citus:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54321:5432"
    volumes:
      - ./pgdata/citus-worker-1-data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - citus-net

  citus-worker-2:
    image: citusdata/citus:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "54322:5432"
    volumes:
      - ./pgdata/citus-worker-2-data:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - citus-net

networks:
  citus-net:
    driver: bridge
